import { test } from 'node:test'
import assert from 'node:assert/strict'
import { createServer } from 'vite'

const server = await createServer({ configFile: false, cacheDir: 'node_modules/.vite-tests', optimizeDeps: { noDiscovery: true, include: [] }, server: { middlewareMode: true }, appType: 'custom' })
const { useBuildingStore: store, EVENT_TIMING: timing } = await server.ssrLoadModule('/src/systems/buildingStore.ts')
const initial = store.getInitialState()
const reset = () => store.setState({ ...initial, incidents: initial.incidents.map(i => ({ ...i })) }, true)
try {
  await test('La anomalía requiere reclamo, cámaras, prueba normal y espera', () => {
    reset()
    store.getState().inspectElevator(); store.getState().answerPhone(); store.getState().tick(100)
    assert.equal(store.getState().stage, 'arrival')
    store.getState().inspectCameras(); store.getState().closeCameras()
    assert.equal(store.getState().stage, 'arrival', 'Mirar cámaras antes del reclamo no salta el inicio')
    store.getState().readLog(); store.getState().inspectElevator()
    assert.equal(store.getState().stage, 'complaint')
    assert.equal(store.getState().incidents[0].status, 'en revisión')
    store.getState().inspectCameras(); store.getState().closeCameras(); store.getState().inspectElevator()
    assert.equal(store.getState().floor, '6')
    store.getState().tick(timing.testing)
    assert.equal(store.getState().floor, 'PB')
    assert.equal(store.getState().anomaly17Visible, false)
    store.getState().tick(timing.normal - .1)
    store.getState().inspectElevator()
    assert.equal(store.getState().stage, 'normal')
    store.getState().tick(.2)
    assert.equal(store.getState().floor, '17')
    store.getState().tick(60)
    assert.equal(store.getState().stage, 'anomaly', 'La llamada espera la comprobación del plano')
    store.getState().readPlan(); store.getState().tick(.1)
    assert.equal(store.getState().stage, 'ringing')
    store.getState().answerPhone(); store.getState().tick(timing.answered)
    assert.equal(store.getState().elevator, 'opening')
    store.getState().tick(timing.opening)
    assert.equal(store.getState().stage, 'end')
    assert.equal(store.getState().elevator, 'held')
    store.getState().readLog(); store.getState().inspectElevator(); store.getState().answerPhone(); store.getState().tick(100)
    assert.equal(store.getState().stage, 'end', 'Las interacciones repetidas no reinician el evento')
  })
  await test('Leer el plano antes de tiempo no revela el 17; CCTV registra la anomalía después', () => {
    reset(); store.getState().readPlan()
    assert.equal(store.getState().anomaly17Visible, false)
    store.getState().readLog(); store.getState().inspectCameras()
    assert.equal(store.getState().cameraAnomalySeen, false)
    store.getState().closeCameras(); store.getState().inspectElevator(); store.getState().tick(timing.testing); store.getState().tick(timing.normal)
    assert.equal(store.getState().stage, 'anomaly')
    store.getState().tick(timing.anomaly)
    assert.equal(store.getState().stage, 'ringing')
    store.getState().inspectCameras()
    assert.equal(store.getState().cameraAnomalySeen, true)
    assert.equal(store.getState().stage, 'ringing')
  })
} finally { await server.close() }
