import { useState } from 'react'
import type { CabalaGameId,CareerState,MiniGameId } from '../world/Architecture'
import { SkillGame } from './SkillGame'
import { LuckGame } from './LuckGame'
import { FootballBall,FootballPitch,FootballPlayerSprite,GoalFrame,StadiumBackdrop,Trophy } from './shared/FootballVisuals'
import { CoachChallenge } from './CoachChallenge'
const skills:Array<{id:MiniGameId;name:string;control:string;number:string}>=[{id:'ball-track',name:'PULSO',control:'5 objetivos · Reflejos',number:'01'},{id:'penalties',name:'DOCE PASOS',control:'Arrastrar · Precisión',number:'02'},{id:'timing-run',name:'EL INSTANTE',control:'Tocar · Timing',number:'03'},{id:'through-pass',name:'ENTRE LÍNEAS',control:'Apuntar · Visión',number:'04'},{id:'personal-run',name:'RUPTURA',control:'Deslizar · Regate',number:'05'},{id:'memory-board',name:'LA SECUENCIA',control:'Recordar · Memoria',number:'06'},{id:'keeper',name:'ÚLTIMA LÍNEA',control:'Reaccionar · Atajadas',number:'07'},{id:'tactic-grid',name:'PIZARRA 3×3',control:'Leer · Bloquear · Definir',number:'08'},{id:'power-shot',name:'EL FIERRAZO',control:'Mantener · Soltar · Potencia',number:'09'}]
const rituals:Array<{id:CabalaGameId;name:string;control:string;number:string}>=[{id:'coin-run',name:'LA MONEDA',control:'Tres lanzamientos',number:'01'},{id:'tower',name:'LA TRIBUNA',control:'Elegí tu sector',number:'02'},{id:'three-cups',name:'LOS TRES VASOS',control:'Seguí la mezcla',number:'03'},{id:'higher-lower',name:'EL PÁLPITO',control:'Tres predicciones',number:'04'},{id:'wheel',name:'EL DESTINO',control:'Girá la rueda',number:'05'}]
function GamePreview({id}:{id:MiniGameId|CabalaGameId}){
  return <div className={'game-preview game-preview--'+id} aria-hidden="true"><FootballPitch/>{id==='ball-track'?<span className="game-preview__target">◎</span>:id==='coin-run'?<span className="game-preview__coin">L</span>:id==='wheel'?<span className="game-preview__wheel">✦</span>:id==='tower'?<><StadiumBackdrop/><span className="game-preview__stand">⚑</span></>:id==='higher-lower'?<span className="game-preview__cards">7 <b>?</b></span>:id==='three-cups'?<span className="game-preview__cups"><i/><i/><i/></span>:<><div className="game-preview__player"><FootballPlayerSprite number={id==='keeper'?'1':'10'} keeper={id==='keeper'} pose={id==='personal-run'?'running':'standing'}/></div>{['penalties','keeper','power-shot'].includes(id)&&<GoalFrame/>}<div className="game-preview__ball"><FootballBall/></div>{(id==='timing-run'||id==='power-shot')&&<span className="game-preview__timing"/>}{(id==='memory-board'||id==='tactic-grid')&&<span className="game-preview__sequence">{id==='tactic-grid'?'3 × 3':'A → B → C'}</span>}</>}</div>
}
export function PlayerGamesHub({career,onSkillScore}:{career:CareerState;onSkillScore:(game:MiniGameId,score:number)=>void}){
  const [mode,setMode]=useState<'skill'|'luck'>(career.finalStyle==='cabulero'?'luck':'skill'),[active,setActive]=useState<MiniGameId|CabalaGameId|null>(null)
  const skill=career.finalStyle==='habilidoso'||(career.finalStyle!=='cabulero'&&mode==='skill')
  if(active)return skill?<SkillGame key={active} game={active as MiniGameId} career={career} onBack={()=>setActive(null)} onComplete={score=>onSkillScore(active as MiniGameId,score)}/>:<LuckGame key={active} game={active as CabalaGameId} onBack={()=>setActive(null)} onComplete={()=>{}}/>
  const games=skill?skills:rituals
  return <section className="game-library"><header><span className="eyebrow">EL CAMPO DE PRUEBAS</span><h2>{skill?'El talento se demuestra.':'Seguí tu intuición.'}</h2><p>{skill?'Nueve maneras de cambiar el partido.':'Cinco rituales. Una señal del destino.'}</p></header>{career.finalStyle!=='cabulero'&&career.finalStyle!=='habilidoso'&&<div className="mixed-games-tabs"><button aria-pressed={skill} className={skill?'active':''} onClick={()=>setMode('skill')}>ϟ VIRTUOSO · 9</button><button aria-pressed={!skill} className={!skill?'active':''} onClick={()=>setMode('luck')}>✦ AL PÁLPITO · 5</button></div>}<div className="game-library__grid">{games.map(game=><button key={game.id} onClick={()=>setActive(game.id)}><GamePreview id={game.id}/><span className="game-library__number">{game.number}</span><div><strong>{game.name}</strong><small>{game.control}</small></div><b className="game-library__play">↗</b></button>)}</div></section>
}
export function CoachGamesHub({onScore}:{onScore:(game:MiniGameId,score:number)=>void}){
  const [active,setActive]=useState<MiniGameId|null>(null)
  if(active)return <CoachChallenge key={active} game={active} onBack={()=>setActive(null)} onScore={score=>onScore(active,score)}/>
  return <section className="game-library"><header><span className="eyebrow">LABORATORIO DEL DT</span><h2>El partido también se lee.</h2></header><div className="game-library__grid">{([{id:'tactics',name:'PIZARRA'},{id:'scouting',name:'OJO CLÍNICO'},{id:'locker',name:'VESTUARIO'},{id:'lineup',name:'ONCE IDEAL'},{id:'negotiation',name:'LA FIRMA'}] as const).map((item,index)=><button key={item.id} onClick={()=>setActive(item.id)}><GamePreview id="through-pass"/><span className="game-library__number">0{index+1}</span><div><strong>{item.name}</strong><small>Leer · Decidir · Ajustar</small></div><Trophy/></button>)}</div></section>
}
