import { useState } from 'react'
import { baseStatsByPosition,statLabels,type FinalStyle,type GameMode,type Position,type PlayerStatKey } from '../world/Architecture'
import { FootballPitch,FootballPlayerSprite,StadiumBackdrop } from '../games/shared/FootballVisuals'
const roles:Array<{id:Position;name:string;identity:string;x:number;y:number;stat:PlayerStatKey}>=[{id:'9',name:'DELANTERO',identity:'GOLEADOR',x:50,y:19,stat:'finishing'},{id:'10',name:'ENGANCHE',identity:'CREADOR',x:50,y:39,stat:'passing'},{id:'7',name:'EXTREMO',identity:'DESEQUILIBRIO',x:82,y:29,stat:'dribbling'},{id:'5',name:'VOLANTE',identity:'EQUILIBRIO',x:28,y:57,stat:'passing'},{id:'2',name:'DEFENSOR',identity:'FUERZA',x:65,y:72,stat:'defending'},{id:'1',name:'ARQUERO',identity:'REFLEJOS',x:50,y:90,stat:'reflexes'}]
export function PositionPicker({value,onChange}:{value:Position;onChange:(value:Position)=>void}){
  const selected=roles.find(role=>role.id===value)??roles[0]
  return <section className="career-position"><header><span className="eyebrow">TU LUGAR EN LA CANCHA</span><h3>Elegí cómo dejar tu marca.</h3></header><div className="career-position__layout"><div className="career-position__pitch"><FootballPitch/>{roles.map(role=><button key={role.id} aria-label={role.name} aria-pressed={value===role.id} style={{left:role.x+'%',top:role.y+'%'}} onClick={()=>onChange(role.id)}>{role.id}</button>)}</div><div className="career-position__identity"><FootballPlayerSprite number={value} keeper={value==='1'}/><span>{selected.identity}</span><strong>{selected.name}</strong><small>{statLabels[selected.stat]} <b>{baseStatsByPosition[value][selected.stat]}</b></small></div></div><div className="career-position__roles">{roles.map(role=><button key={role.id} aria-pressed={value===role.id} onClick={()=>onChange(role.id)}><b>{role.id}</b>{role.name}</button>)}</div></section>
}
export function EntranceScene({mode,onMode}:{mode:GameMode;onMode:(mode:GameMode)=>void}){return <section className="career-entrance"><StadiumBackdrop/><div className="career-entrance__player"><FootballPlayerSprite number="10"/></div><span>CARRERA · DECISIONES · HISTORIA</span><h1>LEGENDS</h1><p>El nombre se gana<br/><em>en la cancha.</em></p><div className="mode-tabs"><button className={mode==='player'?'active':''} onClick={()=>onMode('player')}>SOY JUGADOR</button><button className={mode==='coach'?'active':''} onClick={()=>onMode('coach')}>SOY ENTRENADOR</button></div></section>}
export function FinalStyleChoice({onChoose}:{onChoose:(style:FinalStyle)=>void}){
  const [selected,setSelected]=useState<FinalStyle>('habilidoso')
  const philosophies=[{id:'habilidoso' as const,icon:'ϟ',name:'VIRTUOSO',line:'TODO EN TUS MANOS',copy:'Reflejos, precisión y lectura. Jugás cada final.'},{id:'cabulero' as const,icon:'✦',name:'AL PÁLPITO',line:'QUE DECIDA EL DESTINO',copy:'Rituales, señales y azar. Confiás en tu intuición.'},{id:'mixto' as const,icon:'⇄',name:'MIXTO',line:'INSTINTO + HABILIDAD',copy:'Elegís cómo resolver cada partido decisivo.'}]
  const current=philosophies.find(item=>item.id===selected)!
  return <section className={'career-philosophy career-philosophy--'+selected}><span className="eyebrow">TU FILOSOFÍA · PARA TODA LA CARRERA</span><div className="career-philosophy__preview" aria-hidden="true"><span>{current.icon}</span><i/><i/><i/></div><h2>{current.line}</h2><p>{current.copy}</p><div className="career-philosophy__choices">{philosophies.map(item=><button key={item.id} aria-pressed={selected===item.id} onClick={()=>setSelected(item.id)}><b>{item.icon}</b>{item.name}</button>)}</div><button className="play-button" onClick={()=>onChoose(selected)}>SER {current.name} →</button></section>
}
