import { useState } from 'react'
import { clubById,leagueById,formatMoney,type CareerState,type TransferOffer } from '../world/Architecture'
import { acceptTransferOffer,renewCurrentClub,stayAtClub } from '../systems/buildingStore'
import { ClubCrest } from '../components/ClubIdentity'
import { FootballPlayerSprite,StadiumBackdrop } from '../games/shared/FootballVisuals'
import { GameParticles } from '../games/shared/GameFeedback'
export function MarketScene({state,onState,onDone}:{state:CareerState;onState:(next:CareerState)=>void;onDone:()=>void}){
  const [signed,setSigned]=useState<string|null>(null)
  const club=clubById(state.clubId),offers=state.transferOffers??[],salary=state.currentSalary??club.salary,years=state.contractYearsLeft??0
  const choose=(next:CareerState,message:string)=>{setSigned(message);onState(next)}
  if(signed)return <section className="career-signing"><StadiumBackdrop/><GameParticles gold/><span>EL PRÓXIMO CAPÍTULO</span><ClubCrest name={club.name} size="lg"/><div className="career-signing__shirt"><FootballPlayerSprite number={state.position}/></div><h2>{signed}</h2><p>{club.name} · {state.contractYearsLeft} años</p><button className="play-button" onClick={onDone}>VOLVER A LA CANCHA →</button></section>
  return <section className="career-market"><header className="career-market__header"><span className="eyebrow">{state.marketDecisionRequired?'TU REPRESENTANTE · MERCADO ABIERTO':'TU CONTRATO'}</span><h2>El próximo escudo<br/>lo elegís vos.</h2><div className="career-market__notification"><i>↗</i><div><strong>{offers.length?'TENÉS '+offers.length+' PROPUESTAS':'SIN OFERTAS NUEVAS'}</strong><span>{offers.length?'Deslizá y compará tu futuro.':'Tu historia en el club sigue abierta.'}</span></div></div></header>
    <article className="current-contract-card"><ClubCrest name={club.name} size="lg"/><div><small>CLUB ACTUAL</small><strong>{club.name}</strong><span>{leagueById(club.leagueId).name}</span></div><aside><b>$ {formatMoney(salary)}</b><span>/ mes</span><em>{years>0?years+' AÑOS RESTANTES':'CONTRATO VENCIDO'}</em></aside></article>
    <div className="market-actions">{years>0&&<button disabled={state.retired||!state.marketDecisionRequired} className="stay-button" onClick={()=>choose(stayAtClub(state),'Una temporada más.')}><span><strong>SEGUIR EN {club.short}</strong><small>Cumplir el contrato actual</small></span></button>}<button disabled={state.retired} className="renew-button" onClick={()=>choose(renewCurrentClub(state,3),'La historia continúa.')}><span><strong>RENOVAR POR 3 AÑOS</strong><small>Continuidad y nuevo salario</small></span></button></div>
    {offers.length>0&&<><div className="transfer-offers-head"><span>OFERTAS RECIBIDAS</span><strong>DESLIZÁ →</strong></div><div className="career-offer-track" aria-label="Ofertas de transferencia" tabIndex={0}>{offers.map((offer:TransferOffer,index)=>{const destination=clubById(offer.clubId);return <article key={offer.clubId} className="career-offer"><div className="career-offer__number">0{index+1}<span>NUEVA OFERTA</span></div><ClubCrest name={destination.name} size="lg"/><span>{leagueById(destination.leagueId).name}</span><h3>{destination.name}</h3><b className="career-offer__role">{offer.role}</b><dl><div><dt>SALARIO MENSUAL</dt><dd>$ {formatMoney(offer.salary)}</dd></div><div><dt>CONTRATO</dt><dd>{offer.years} AÑOS</dd></div><div><dt>PRIMA DE FIRMA</dt><dd>$ {formatMoney(offer.signingBonus)}</dd></div></dl><small>Tu reputación viaja con vos. La huella en el nuevo club empieza de cero.</small><button disabled={state.retired} className="play-button" onClick={()=>choose(acceptTransferOffer(state,offer),'Bienvenido a tu nueva casa.')}>FIRMAR CON {destination.short} →</button><button className="career-offer__reject" disabled={state.retired} onClick={()=>onState({...state,transferOffers:offers.filter(item=>item.clubId!==offer.clubId),offers:state.offers.filter(id=>id!==offer.clubId)})}>RECHAZAR PROPUESTA</button></article>})}</div></>}
  </section>
}
